# 分析結果のプレゼンテーション

## このトピックでやるべきこと


1. 分析結果をレポートにまとめて提出する。
2. 分析結果の概要を発表する。
3. 他の受講生のプレゼンテーションを視聴する。

以下の説明をよく読み、レポートとプレゼンテーションを用意すること。

## 分析結果のレポート（期末レポート）

### レポートの内容

以下の内容を含むレポートを提出しなさい。

1. リサーチクエスチョン
2. 分析計画のプレゼンテーションで発表した計画からの変更点
  - 変更点がない場合は不要
  - 計画全体を大幅に変更した（たとえば、リサーチクエスチョンを変えた）場合は、研究計画のプレゼンテーションで要求された内容も含めること
3. 推定に用いた方法と統計モデル（推定に利用する式）
4. 分析に用いたデータの説明
5. 分析結果を示す図（図がないものは減点する）
6. 分析結果の解釈
  - 「統計的に有意」だけでは不十分：統計的に有意だからどうした？
7. リサーチクエスチョンに対する回答
8. どういうデータ（今回の分析では手に入らなかったが、自分が理想とするデータ）があれば、因果効果の推定がもっとうまくいくと考えられるか？
  - 注意：「うまくいく」は、統計的に有意な結果を出すことではない。
  
### レポートの形式と提出方法

**形式**

- レポートはR Markdown で書く
- R Markdown を knit してPDF ファイルを作る


**提出するファイル**

1. R Markdown ファイル
  - ファイル名：metrics_final_LastFirst.Rmd
2. PDF ファイル
  - ファイル名：metrics_final_LastFirst.pdf
  - レポートに必要ないと思われるモノ（例：Rのwarnigs）は、見えないようにすることが望ましい
3. 分析に使ったデータセット
  - 私と共有できない事情がある場合は提出しなくてもよいが、提出期限より前に（できれば分析計画のプレゼンの際に）申し出ること
    - 共有できない例：他の教員と共同で実施した実験データで、そのデータを使ってこれから論文を書く予定
    - 共有できない例：データの利用申請を提出して手に入れたデータ
  - Rで読み込みめれば形式は自由（例：.csv, .tsv, Rds）
  - ファイル名は自由（よく考えてファイル名を付けるように）
  - データセットは複数のファイルに分かれていても良い
  - データを提出できない場合は、データに関する詳しい説明をレポートに含めること
  
  
**提出方法**

- Slack のダイレクトメッセージで提出
- **提出期限：8月5日（水）正午**（日本時間）


## 分析結果のプレゼンテーション

### プレゼンテーションの内容

分析結果の概要を発表してもらう。時間に限りがあるので、分析結果のうち自分が注目すべきだと思う点に焦点を絞って発表すること。

プレゼンテーション時間は**5分以上10分以内を目安**とする（多少の時間超過は見逃すので、動画編集に余計な時間を費やす必要はない）。

プレゼンテーション動画の作り方について、[Topic 7](midterm-presentation.html) を参照。


### 提出方法と提出期限

- 提出方法：Slack の **# プレゼン2_分析結果** チャンネルに投稿する。
- 提出するファイル（2つ提出）
  1. プレゼンテーションの動画
  
    - MP4 または M4V のファイル
    - ファイル名：metrics_result_LastFirst.mp4 （または metrics_result_LastFirst.m4v）
  
  2. プレゼンテーションに使用したスライド
  
    - 必ず **PDF ファイル** に変換すること
    - ファイル名：metrics_result_LastFirst.pdf

- **提出期限：8月5日（水）正午**（日本時間）    

