---
title: "KUT 計量経済学応用"
subtitle: "統計的因果推論入門"
author: "矢内 勇生"
date: "`r Sys.Date()` 更新（2020-06-07 公開）"
site: bookdown::bookdown_site
documentclass: book
bibliography: ["metrics2ref.bib"]
link-citations: yes
nocite: |
  @r2020
---

```{r global_option, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = TRUE, message = FALSE, 
                      fig.height = 2, fig.width = 3.5,
                      knitr.kable.format = "markdown")
```


# はじめに {-}

## この資料について

この資料は、高知工科大学 (KUT) 経済・マネジメント学群で2020年度に開講する「計量経済学応用」の補助教材である。

受講生は、以下の3点に注意されたい。

1. この資料は、授業の進捗にあわせてアップデートされる。
  - 公開時点（2Q開始時点）では、すべてのトピックの説明が完成していない。
  - 各トピックの説明は順次追加する。
  - 一度アップロードしたトピックの内容を修正するときは、Slack でアナウンスする。
  - ただし、誤字・脱字等については気付いたらアナウンスせずに修正する。

2. この資料以外の授業資料（解説音声付きスライドや配布資料など）は、[KUTLMS (Moodle)](https://lms.kochi-tech.ac.jp/course/view.php?id=793) にアップロードする。

3. この資料以外に教科書が必要である。
  - 教科書：安井翔太. 2020.『[効果検証入門：正しい比較のための因果推論/計量経済学の基礎](https://gihyo.jp/book/2020/978-4-297-11117-5)』（技術評論社）
    - 購入するのは電子版（たとえば、Kindle版）でも良い。

## 履修条件

この授業は、「計量経済学」（とその前提となる「統計学2」）を履修済みであることを前提に進める。そのため、この授業（この資料）では：

- 基本的な統計用語・統計量（例：分散、共分散、最小二乗推定量、有意水準）や基本的な手続き（例：仮説検定）は説明しない。
- R とRStudio の基本的な使い方は説明しない。以下を思い出しておくこと。
  - RStudio のプロジェクト機能の使い方。
  - ggplot2 による作図の方法。
  - RMarkdownの書き方。特に、文章とコードチャンクの使い分け。

これらの点に不安がある場合は、2Qの早い時期（6月の第3週頃まで）に自分で計量経済学の内容を学習（復習）するか、今年度の3Qに「計量経済学」を受講してから、来年度の「計量経済学応用」を受講すること。自分で学習する場合は、最低でも浅野正彦・矢内勇生『[Rによる計量政治学](https://github.com/yukiyanai/quant-methods-R)』（2018年、オーム社）の第4章から第14章までの内容を学習すること。

## R とRStudio のインストール

RとRStudio を自分のパソコンにインストールして使いたい場合は、私が作った以下の資料を参照されたい。

- [Linux (Ubuntu) 編](http://yukiyanai.github.io/jp/resources/docs/install-R_ubuntu.pdf) (PDF, 4.6MB)
- [macOS 編](http://yukiyanai.github.io/jp/resources/docs/install-R_macOS.pdf) (PDF, 4.9MB)
- [Windows 編](http://yukiyanai.github.io/jp/resources/docs/install-R_windows.pdf) （PDF, 5.8MB)

## 授業計画

以下の内容を扱う予定である（カッコ内は何回目の授業で扱うかの目安）。

1. イントロダクション（第1回）
2. セレクションバイアス（第2回）
3. RCT（第3回）
4. 回帰分析（第4回、第5回）
5. 傾向スコア（第6回、第7回）
6. パネルデータ分析（第8回、第9回）
8. 分析計画のプレゼンテーション（第10回）
9. 回帰不連続デザイン（第11回、第12回）
10. 操作変数法（第13回、第14回）
11. 分析結果のプレゼンテーション（第15回）

各トピックの参考文献や予習課題については、[シラバス（PDFファイル）](http://yukiyanai.github.io/jp/classes/econometrics2/docs/syllabus-applied-econometrics_2020-2Q.pdf) を参照されたい。

この資料は上に挙げたトピック単位で作成している。各トピックに例として書かれたRコードは、トピックを途中から実行することを想定していない。たとえば、1.3.6節に書いてあるコードを実行するためには、トピック1の冒頭から 順番にRコードを実行する必要がある。途中のコードだけ実行しても動かない可能性が高い。

他方、各トピックは独立に実行できる。例えば、トピック3に書かれているコードを実行するために、トピック2に書かれたRコードを実行する必要はない。トピック3の冒頭から実行すれば十分である。
ただし、トピック1の内容は全員1度は実行済みであると仮定する。1度実行すれば、Rをインストールし直すか、バージョンアップするまで再度実行する必要はない。

## License {-}

The text of this work is licensed under the [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). The R Code in this work is licensed under the [MIT License](license.txt).

