# 分析計画のプレゼンテーション

## このトピックでやるべきこと

1. **自分の分析計画のプレゼンテーションを行う！**
2. 他の受講生のプレゼンテーションを視聴する。
3. 他の受講生の分析計画にコメントする。
  - 各自、自分以外の2人のプレゼンテーションにコメントする。
  - 誰がどのプレゼンテーションにコメントするかは、担当教員が決める。
  - 割り当てられていない相手のプレゼンテーションにコメントすることは自由。


以下の説明をよく読んでプレゼンテーションを用意すること。

この課題には事前の準備が必要なので、早めに取り組むこと。特に、**自分の研究に使えそうなデータを探す必要がある**ことに注意。


## 分析計画のプレゼンテーション

### プレゼンテーションの内容

以下の内容を**すべて含む**プレゼンテーションを行いなさい。

1. 因果効果（処置効果）に関するリサーチクエスチョン
  - 特定したい因果効果を明確にすること
    - 例：「大学への進学は、生涯賃金を増やすか？」
    - 例：「猫を飼うと、大学の成績は良くなるか？」
2. 研究の対象となる母集団
3. 因果効果の推定に用いる方法
4. 因果効果の推定に用いるデータ
5. 自分が選んだデータと推定方法で、自分のリサーチクエスチョンに答えらえると考える理由

プレゼンテーション時間は**5分以上10分以内を目安**とする（多少の時間超過は見逃すので、動画編集に余計な時間を費やす必要はない）。

スライドを作る際は、[伝わるデザイン](https://tsutawarudesign.com/) を参考に。

### プレゼンテーションの方法

**プレゼンテーションの条件**：スライドを用いた音声つきの動画でプレゼンテーションを行うこと。


動画ファイルは、できれば MP4 形式 (.mp4) または M4V 形式 (.m4v) が望ましい。MP4またはM4V にできないときは相談してほしい。

その他の内容・動画の作り方は自由。自分の姿を写すかどうかも自由。動画は Slack で共有するので、私だけでなく、他の受講生も全員視聴することに注意。


自宅で声が出せない事情がある場合は、6月中に連絡してほしい。


### プレゼンテーション動画の作成法

動画の作成法は自由である。例として、簡単な動画の作り方をいくつか提案し、それぞれの方法についての説明が記載されているウェブサイトを紹介する。他に良い方法があれば、Slack で共有してほしい。

#### Zoom ミーティングを録画する

Zoom のミーティングを1人で行い、スライド画面を共有して録画すれば動画 (MP4 ファイル）ができる。おそらく、これが1番簡単である。

- [参考1](https://zoom.nissho-ele.co.jp/blog/manual/zoom-recording.html)
- [参考2](https://symphonict.nesic.co.jp/workingstyle/zoom/recording/)
- [参考3](https://dime.jp/genre/897364/)

注意：無料版の Zoom ではクラウドレコーディングが使えないので、ローカルレコーディングを使う。


#### Keynote プレゼンテーションに音声を付ける

MacのKeynote でスライドを作った場合は、この方法が使える。

- [参考4](https://support.apple.com/ja-jp/guide/keynote/tan8a5df9cc5/mac)
- [参考5](http://urusulambda.com/2020/04/14/mac%E3%81%A7%E7%84%A1%E6%96%99%E3%81%A7%E5%8B%95%E7%94%BB%E3%82%92%E4%BD%9C%E3%82%8B%E3%81%AE%E3%81%ABkeynote%E3%81%8C%E6%84%8F%E5%A4%96%E3%81%A8%E3%81%84%E3%81%84%E3%81%8B%E3%82%82/)
- [参考6](https://www.youtube.com/watch?v=UOfa50lqVIg)


#### PowerPoint に音声を付ける

Microsoft Office PowerPoint でスライドを作った場合は、この方法が使える。

- [参考7](https://note.com/dr_kano/n/n6c7809d2ebe8)
- [参考8](https://kagakucafe.com/202004095777.html)
- [参考9](https://www.fonepaw.jp/tutorials/convert-powerpoint-to-video.html)

注意：ファイルを保存する際は、MP4を選択する。


### 提出方法と提出期限

- 提出方法：Slack の **# プレゼン1_分析計画** チャンネルに投稿する。
- 提出するファイル（2つ提出）
  1. プレゼンテーションの動画
  
    - MP4 または M4V のファイル
    - ファイル名：metrics_mid_LastFirst.mp4 （または metrics_mid_LastFirst.m4v）
  
  2. プレゼンテーションに使用したスライド
  
    - 必ず **PDF ファイル** に変換すること
    - ファイル名：metrics_mid_LastFirst.pdf

- **提出期限：7月17日（金）正午**（日本時間）    

## 他の受講生へのコメントについて

この**コメントも成績評価の対象**になる。提出までの期間が短いので注意。

- コメントの内容
  - 分析計画の良いところをできるだけたくさん見つける。
  - 計画の良くないところを批判する（その研究を改善することが目的であることを忘れずに）
    - 良くないと思う理由をできるだけわかりやすく説明する。
    - どうすればもっと良くなるか、代替案を提示する。
- 提出するファイル
  - コメントをまとめた PDF ファイル
    - 2人に対するコメントを1つのファイルにまとめる。
    - 誰に対するコメントかわかるようにすること。
  - ファイル名：metrics_comment_LastFirst.pdf
  - 分量は自由（目安：1つの報告に対し1ページ）
  - 提出方法：Slack の **# プレゼン1_分析計画** チャンネルに投稿する。
    - 7月17日（金）の正午以降に投稿すること。
  - **提出期限：7月21日（火曜）正午**（日本時間）      
    - 自分がコメントを担当する相手のプレゼンテーションが締切までに提出されなかったときは、遅れた分だけこの締め切りも延ばす（Slack上の投稿日時を基準にする）。




  

